#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  OS::TripleO::Compute::Net::SoftwareConfig: ../compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: ../controller.yaml

  # Ceph storage nodes configs.
  OS::TripleO::CephStorage::Net::SoftwareConfig: ../ceph-storage.yaml

  OS::TripleO::NodeUserData: ../first-boot.yaml
  OS::TripleO::NodeExtraConfigPost: ../post-install.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.2.4
  ControlPlaneIp: 192.0.2.4
  EC2MetadataIp: 192.0.2.4  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  TenantNetCidr: 172.16.0.0/24
  ExternalNetCidr: 10.19.111.0/24
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 1020
  StorageNetworkVlanID: 1030
  StorageMgmtNetworkVlanID: 1040
  TenantNetworkVlanID: 1050
  ExternalNetworkVlanID: 111
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.19.111.23', 'end': '10.19.111.50'}]
  ExternalNetworkVip: 10.19.111.51

  # Specify the NTP server for nodes to use
  NtpServer: 10.5.26.10

  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 10.19.111.254

  DnsServers: ["10.16.36.29","10.11.5.19"]

  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"

  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # LinuxBondInterfaceOptions: "mode=802.3ad" <== Don't use this use next one specifying details to make it faster
  LinuxBondInterfaceOptions: "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceOvsOptions: "bond_mode=active-backup lacp=active"

  # Set to 9000 for Jumbo frames
  #NeutronGlobalPhysnetMtu: 9000 

  # Flavor of controller and compute nodes:
  OvercloudControlFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudCephStorageFlavor: ceph-storage
  
  # Number of nodes to deploy.
  ControllerCount: 1
  ComputeCount: 1
  CephStorageCount: 0
  
  NeutronNetworkVLANRanges: "datacentre:1000:1999,physnet_sriov1:2000:2099,physnet_sriov2:2100:2199"

  ##################################
  # Common performance paramenters
  ##################################

  #ComputeKernelArgs: "iommu=pt intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=12 isolcpus=12-23"

  # Add a list or range of physical CPU cores to be reserved for virtual machine processes
  #NovaVcpuPinSet: ['16-23']
 
  # Set the tunnel type for tenant network (for example, vxlan or gre). To disable the tunnel type parameter, set the value to ""
  NeutronTunnelTypes: ""
 
  # Set the tenant network type for OpenStack Networking. The options available are vlan or vxlan:
  NeutronNetworkType: 'vlan'

  NeutronNetworkVLANRanges: "datacentre:1000:1999,physnet_sriov1:2000:2099,physnet_sriov2:2100:2199"

  ##################################
  # SR-IOV paramenters
  ##################################
  
  NeutronSupportedPCIVendorDevs: ['8086:1584','8086:154c']

  NeutronPhysicalDevMappings: "physnet_sriov1:ens1f2,physnet_sriov2:ens1f3"
  
  # Number of VFs that needs to be configured for a physical interface
  NeutronSriovNumVFs: "ens1f2:5,ens1f3:5"
  
  NovaPCIPassthrough:
    - devname: "ens1f2"
      physical_network: "physnet_sriov1"
    - devname: "ens1f3"
      physical_network: "physnet_sriov2"
      
  NeutronMechanismDrivers: ['sriovnicswitch','opendaylight_v2']
  
  NovaSchedulerDefaultFilters: ['RetryFilter','AvailabilityZoneFilter','RamFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter','PciPassthroughFilter','NUMATopologyFilter']
  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]
  
  ComputeKernelArgs: "pci=realloc intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=12 rdblacklist=i40evf"

  ##################################
  # ODL paramenters
  ##################################
  
  OpenDaylightProviderMappings: 'odl:br-odl'
