#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  OS::TripleO::Compute::Net::SoftwareConfig: ../compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: ../controller.yaml

  # Ceph storage nodes configs.
  OS::TripleO::CephStorage::Net::SoftwareConfig: ../ceph-storage.yaml

  OS::TripleO::NodeUserData: ../firstboot/first-boot.yaml
  OS::TripleO::NodeExtraConfigPost: ../post-install.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.2.4
  ControlPlaneIp: 192.0.2.4
  EC2MetadataIp: 192.0.2.4  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  TenantNetCidr: 172.16.0.0/24
  ExternalNetCidr: 10.19.111.0/24
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 1020
  StorageNetworkVlanID: 1030
  StorageMgmtNetworkVlanID: 1040
  TenantNetworkVlanID: 1050
  ExternalNetworkVlanID: 111
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.19.111.23', 'end': '10.19.111.50'}]
  ExternalNetworkVip: 10.19.111.51

  # Specify the NTP server for nodes to use
  NtpServer: 10.5.26.10

  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 10.19.111.254

  DnsServers: ["10.16.36.29","10.11.5.19"]

  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"

  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # LinuxBondInterfaceOptions: "mode=802.3ad" <== Don't use this use next one specifying details to make it faster
  LinuxBondInterfaceOptions: "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceOvsOptions: "bond_mode=active-backup lacp=active"

  # Set to 9000 for Jumbo frames
  #NeutronGlobalPhysnetMtu: 9000 

  # Flavor of controller and compute nodes:
  OvercloudControlFlavor: control
  OvercloudComputeFlavor: compute
  OvercloudCephStorageFlavor: ceph-storage
  
  # Number of nodes to deploy.
  ControllerCount: 1
  ComputeCount: 1
  CephStorageCount: 1

  ##################################
  # Common paramenters
  ##################################
 
  # Set the tunnel type for tenant network (for example, vxlan or gre). To disable the tunnel type parameter, set the value to ""
  NeutronTunnelTypes: ""
 
  # Set the tenant network type for OpenStack Networking. The options available are vlan or vxlan:
  NeutronNetworkType: 'vlan'

  NeutronNetworkVLANRanges: "datacentre:1000:2000,dpdk:2001:3000"

  NeutronBridgeMappings: 'datacentre:br-all,dpdk:br-ex'

  ##################################
  # DPDK parameters
  ##################################

  DpdkBondInterfaceOvsOptions: "bond_mode=balance-tcp lacp=active"

  ComputeKernelArgs: "iommu=pt intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=12 isolcpus=0-11"

  # List of cores to be used for DPDK Poll Mode Driver
  NeutronDpdkCoreList: "'0,1,2,3'"

  # NeutronDpdkSocketMemory
  NeutronDpdkSocketMemory: "'2048,2048'"

  NeutronDpdkDriverType: "vfio-pci"

  NeutronDpdkMemoryChannels: "4"

  NeutronDatapathType: "netdev"

  NeutronVhostuserSocketDir: "/var/run/openvswitch"

  NovaReservedHostMemory: "4096"

  # Add a list or range of physical CPU cores to be reserved for virtual machine processes
  NovaVcpuPinSet: ['4-11']

  NovaSchedulerDefaultFilters: "RamFilter,ComputeFilter,AvailabilityZoneFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,PciPassthroughFilter,NUMATopologyFilter"

  # Set a list or range of physical CPU cores that should be excluded from tuning:
  HostCpusList: "'12,13,14,15,16,17,18,19,20,21,22,23,36,37,38,39,40,41,42,43,44,45,46,47'"  

  # HostIsolatedCoreList = NeutronDpdkCoreList(0-3) + NovaVcpuPinSet(4-11)
  HostIsolatedCoreList: "0-11"
